version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      MONGODB_URL: "mongodb://database:27017/mydb"
    volumes:
      - database-volume:/app/database

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - webapp
    environment:
      API_URL: "http://webapp:3000"

volumes:
  database-volume:
  mongodb-data:
